#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "$ROOT_DIR/scripts/lib.sh"
load_bootstrap_env "${1:-}"

: "${NOTEBOOKLM_HERMES_SKILL_REPO:?missing NOTEBOOKLM_HERMES_SKILL_REPO}"
: "${NOTEBOOKLM_PY_REPO:?missing NOTEBOOKLM_PY_REPO}"
: "${LANCEDB_PRO_HERMES_PLUGIN_REPO:?missing LANCEDB_PRO_HERMES_PLUGIN_REPO}"
: "${CODEX_DISPATCH_HERMES_PLUGIN_REPO:?missing CODEX_DISPATCH_HERMES_PLUGIN_REPO}"
: "${NOTEBOOKLM_HERMES_SKILL_DIR:?missing NOTEBOOKLM_HERMES_SKILL_DIR}"
: "${NOTEBOOKLM_PY_DIR:?missing NOTEBOOKLM_PY_DIR}"
: "${LANCEDB_PRO_HERMES_PLUGIN_DIR:?missing LANCEDB_PRO_HERMES_PLUGIN_DIR}"
: "${CODEX_DISPATCH_HERMES_PLUGIN_DIR:?missing CODEX_DISPATCH_HERMES_PLUGIN_DIR}"

note "Preparing repository checkouts under $REPOS_DIR"
ensure_repo "$NOTEBOOKLM_HERMES_SKILL_REPO" "$NOTEBOOKLM_HERMES_SKILL_DIR"
ensure_repo "$NOTEBOOKLM_PY_REPO" "$NOTEBOOKLM_PY_DIR"
ensure_repo "$LANCEDB_PRO_HERMES_PLUGIN_REPO" "$LANCEDB_PRO_HERMES_PLUGIN_DIR"
ensure_repo "$CODEX_DISPATCH_HERMES_PLUGIN_REPO" "$CODEX_DISPATCH_HERMES_PLUGIN_DIR"

note "Repositories are ready"
